### ISSUE TITLE
Is it possible to choose more from more than one list?

### ISSUE THREAD

**Issue by Codesesh** [mediabeastnz/campaign-monitor-userform#5]
We have a situation where we want to be able to access 2x lists. By the looks of the docs we can only access one list by providing the API key and client ID for that list..

I see in campaign monitor there is a Administrator API key which states "This API key can access all of your client data. Wherever possible, use client API keys instead."

```
Administrator API key

API key	
XXXXXXXXXXXXXXXXXXXXXXX
Important: This API key can access all of your client data. Wherever possible, use client API keys instead.
```

I tried to use this but because it doesn't have a client ID it just disables the subscribers dropdown list in silverstripe.

Any work arounds for this?

**Comment by mylesthedev** [comment]
Sorry do you mean get all lists from all clients from your CM account?

**Comment by Codesesh** [comment]
@mediabeastnz - Yip I think that would be the only way to go about it since we want to be able to have access to 2x different client lists.

**Comment by mylesthedev** [comment]
Hmm I don't think the API allows toy to do that. You'd have to write an extension which then calls the API and loops through each client. While looping through each client you'd need to do another API call which gets the lists.

Once you have the lists you can use this extension hook to update the dropdown in the CMS to include all your new lists.  https://github.com/mediabeastnz/campaign-monitor-userform/blob/master/code/extensions/EditableCampaignMonitorField.php#L235

It's quite a custom requirement and probably doesn't make sense to add it to the module sorry.
